### ISSUE TITLE
Http not working anymore with maven

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#401]
### Summary of the Bug
```
java.io.IOException: Reason: HTTPS Required
        at org.eclipse.sw360.antenna.util.HttpHelper.downloadFile(HttpHelper.java:49) ~[runtime-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.maven.HttpRequester.tryFileDownload(HttpRequester.java:87) ~[maven-module-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.maven.HttpRequester.requestFile(HttpRequester.java:64) ~[maven-module-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.maven.workflow.processors.enricher.MavenArtifactResolverImpl.resolve(MavenArtifactResolverImpl.java:130) ~[maven-module-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.maven.workflow.processors.enricher.MavenArtifactResolverImpl.resolveArtifacts(MavenArtifactResolverImpl.java:106) ~[maven-module-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.maven.workflow.processors.enricher.MavenArtifactResolverImpl.process(MavenArtifactResolverImpl.java:81) ~[maven-module-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.maven.workflow.processors.enricher.MavenArtifactResolver.process(MavenArtifactResolver.java:61) ~[maven-module-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.api.workflow.AbstractProcessor.process(AbstractProcessor.java:20) ~[model-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.workflow.AntennaWorkflow.applyProcessors(AntennaWorkflow.java:112) ~[runtime-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.workflow.AntennaWorkflow.execute(AntennaWorkflow.java:54) ~[runtime-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.core.AntennaCore.compose(AntennaCore.java:51) ~[runtime-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.frontend.stub.cli.AbstractAntennaCLIFrontend.execute(AbstractAntennaCLIFrontend.java:94) ~[cli-frontend-stub-1.0.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.antenna.frontend.cli.AntennaCLIFrontend.main(AntennaCLIFrontend.java:44) ~[classes/:?]
        at org.eclipse.sw360.antenna.frontend.cli.AntennaCLIFrontendTest.lambda$testExecutionUsingMainMethod$0(AntennaCLIFrontendTest.java:42) ~[test-classes/:?]
        at org.eclipse.sw360.antenna.frontend.testing.AbstractAntennaFrontendTest.protoypeExecutionTest(AbstractAntennaFrontendTest.java:244) [antenna-test-project-asserter.jar:?]
        at org.eclipse.sw360.antenna.frontend.cli.AntennaCLIFrontendTest.testExecutionUsingMainMethod(AntennaCLIFrontendTest.java:39) [test-classes/:?]
```
Reason: https://www.alphabot.com/security/blog/2020/java/Your-Java-builds-might-break-starting-January-13th.html

### Steps to reproduce
- run example-project with cli

### Acceptance Criteria
- [x] change urls
- [x] include check in http requester or maven module 

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-01-23
